---
- name: install jemalloc
  apt:
    pkg: libjemalloc-dev=3.6.0-9ubuntu1
    state: present
  become: true

- name: ensure user level systemd dir exists
  file:
    path: /home/{{ deploy_user }}/.config/systemd/user/
    state: directory
  become: true
  become_user: "{{ deploy_user }}"

- name: copy sidekiq parent process systemd file
  template:
    src: config/systemd/user/sidekiq.service
    dest: /home/{{ deploy_user }}/.config/systemd/user/sidekiq.service
  become: true
  become_user: "{{ deploy_user }}"

- name: copy sidekiq systemd file
  template:
    src: config/systemd/user/sidekiq@.service
    dest: /home/{{ deploy_user }}/.config/systemd/user/sidekiq@.service
  become: true
  become_user: "{{ deploy_user }}"

- name: enable sidekiq
  systemd:
    name: sidekiq.service
    enabled: yes
    scope: user
  become: true
  become_user: "{{ deploy_user }}"

- name: force reload service file
  systemd:
    daemon_reload: yes
    scope: user

- name: restart sidekiq
  systemd:
    name: sidekiq.service
    state: restarted
    scope: user
  tags: restart-sidekiq
  become: true
  become_user: "{{ deploy_user }}"
