# Ansistrano after symlink tasks
---
- name: Fix bundler path for bootboot
  command: sed -i "s#{{ ansistrano_releases_path }}/[0-9,Z]\+/#{{ ansistrano_shared_path }}/#g" {{ ansistrano_shared_path }}/.bundle/plugin/index
- name: Install required gems
  bundler:
    chdir: "{{ ansistrano_release_path.stdout }}"
    executable: "{{ bundle_path }}"
    deployment_mode: yes
    exclude_groups:
      - development
      - test

- name: precompile assets
  command: "{{ bundle_path }} exec rake assets:precompile"
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: migrate the db
  command: "{{ bundle_path }} exec rake db:migrate:with_data"
  run_once: true
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: update the crontab
  command: "{{ bundle_path }} exec whenever --update-crontab simple-server --set environment=production"
  run_once: true
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
