- name: install dependencies necessary to connect to VPN
  apt:
    pkg:
      - libnss3-tools
      - firefox
    state:
      latest
  become: true

- name: ensure /opt/sslvpn-plus exists
  file:
    path: /opt/sslvpn-plus
    state: directory

- name: Unarchive sslvpn-plus install script
  unarchive:
    src: linux_phat_client.tgz
    dest: /home/deploy
    creates: /home/deploy/linux_phat_client

- name: Install sslvpn-plus client
  expect:
    chdir: /home/deploy/linux_phat_client
    command: ./install_linux_phat_client.sh
    responses:
      Do you want to continue: y
  become: true

- name: ensure user level systemd dir exists
  file:
    path: /home/deploy/.config/systemd/user/
    state: directory
  become: true
  become_user: deploy

# - name: copy vpn connection systemd file
#   template:
#     src: config/systemd/user/cphc_vpn.service
#     dest: /home/deploy/.config/systemd/user/cphc_vpn.service
#   become: true
#   become_user: deploy

# - name: force reload service file
#   systemd:
#     daemon_reload: yes
#     scope: user

# - name: enable sidekiq
#   systemd:
#     name: cphc_vpn.service
#     enabled: yes
#     scope: user
#   become: true
#   become_user: deploy

# - name: restart cphc vpn connection
#   systemd:
#     name: cphc_vpn.service
#     state: restarted
#     scope: user
#   tags: restart-cphc-vpn
#   become: true
#   become_user: deploy
