# rbenv tasks
---
- name: clone rbenv git repo
  git:
    repo: "https://github.com/sstephenson/rbenv.git"
    dest: "~/.rbenv"
    accept_hostkey: "yes"
  become: true
  become_user: deploy

- name: include rbenv in $PATH
  lineinfile: >
    dest=~/.bashrc
    line='export PATH="$HOME/.rbenv/bin:$PATH"'
    state=present
    insertafter=EOF
  become: true
  become_user: deploy

- name: load rbenv in .bashrc
  lineinfile: >
    dest=~/.bashrc
    line='eval "$(rbenv init -)"'
    state=present
    insertafter=EOF
  become: true
  become_user: deploy

- name: clone ruby-build git repo
  git:
    repo: "https://github.com/sstephenson/ruby-build.git"
    dest: "~/.rbenv/plugins/ruby-build"
    accept_hostkey: "yes"
  become: true
  become_user: deploy

- name: include ruby-build in $PATH
  lineinfile: >
    dest=~/.bashrc
    line='export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"'
    state=present
    insertafter=EOF
  become: true
  become_user: deploy

- name: clone rbenv-gem-rehash git repo
  git:
    repo: "https://github.com/sstephenson/rbenv-gem-rehash.git"
    dest: "~/.rbenv/plugins/rbenv-gem-rehash"
    accept_hostkey: "yes"
  become: true
  become_user: deploy

- name: install ruby 2.7.4
  shell: rbenv install -s 2.7.4
  environment:
    PATH: "/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-builds/bin:{{ ansible_env.PATH }}"
  become: true
  become_user: deploy

- name: make ruby global
  shell: rbenv global 2.7.4
  environment:
    PATH: "/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-builds/bin:{{ ansible_env.PATH }}"
  become: true
  become_user: deploy

- name: rbenv rehash
  shell: rbenv rehash
  environment:
    PATH: "/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-builds/bin:{{ ansible_env.PATH }}"
  become: true
  become_user: deploy

- name: set up .gemrc
  lineinfile: >
    dest=~/.gemrc
    line='gem: --no-ri --no-rdoc'
    state=present
    create=yes
    insertafter=EOF
  become: true
  become_user: deploy

- name: install bundler
  shell: ~/.rbenv/shims/gem install bundler -v {{bundler_version}}
  become: true
  become_user: deploy

- name: update system gems
  shell: ~/.rbenv/shims/gem update --system
  become: true
  become_user: deploy
