---
- hosts: rails
  roles:
    - { role: ssh, tags: ['ssh'] }
    - { role: simple-server, tags: ['simple-server'] }
- hosts: sidekiq
  roles:
    - { role: sidekiq, tags: ['sidekiq'] }
- hosts: cphc_migration
  roles:
    - { role: cphc_migration, tags: ['cphc_migration'] }
