# simple server tasks
---
- name: Deploy | Include secrets
  include_vars:
    file: "{{ deploy_env }}/secrets.yml"
    name: secrets
  tags: update-app-config

- name: Deploy | Create apps directory
  file:
    path: "{{ ansistrano_deploy_to }}/shared"
    state: directory
    owner: "{{ deploy_user }}"

- name: Deploy | Copy .env template file
  template:
    src: .env.j2
    dest: "{{ ansistrano_deploy_to }}/shared/.env.production"
  tags: update-app-config
